### ISSUE TITLE
Looks great

### ISSUE THREAD

**Issue by binnisb** [martinjo/obsidian-gym-log#1]
Hey. This looks awesome. 

I am adding this to my vault, do you have documentation how you configure the plugins? If not, then I can submit a pr with documentation for that :)

**Comment by binnisb** [comment]
Wondering if you can commit a vault with the plugin configs? Then I can replicate and document.

**Comment by binnisb** [comment]
I think I have the config for dataview and customJS, but the QuickAdd is a bit harder :) Would really appreciate it if you can share how that is set up.

**Comment by mb-beep** [comment]
Same, found out all configs, but buttons seem not to work, would appreciate if you could show us how it works :)

This gym log is exactly what I was looking for!

**Comment by martinjo** [comment]
I understand that the quickadd config is a bit tricky. Promise to provide the needed info as soon as I find the time! Hopefully in the beginning of next week.

**Comment by martinjo** [comment]
I've updated the Readme to include instructions on how QuickAdd is configured. I've also commited the .obsidian folder containing the configurations files for the vault, so it should contain everything needed to work now.

Do you need anything more to get it working on your end?

**Comment by binnisb** [comment]
I will try it out tomorrow :) Thanks!

**Comment by binnisb** [comment]
It works now and looks like all the settings synced as well. 

Looking forward to try it out ! Thanks!
